In [1]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")
# Task 1.1: Create a 1D array with numbers from 0 to 99
arr1_1 = np.arange(0, 100)

# Task 1.2: Create a 3x3 array filled with ones
arr1_2 = np.ones((3, 3))

# Task 1.3: Create a 2x4 array filled with the number 7
arr1_3 = np.full((2, 4), 7)

# Task 1.4: Create a 5x5 array with random integers between 10 and 50 (inclusive)
arr1_4 = np.random.randint(10, 51, size=(5, 5))

# Display the results
print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[15 15 11 50 18]
 [26 42 28 22 42]]


In [5]:
import numpy as np

print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

# 2.1 Extract the element at row 2, column 3 (0-indexed)
val2_1 = data[2, 3]

# 2.2 Extract the first row
row2_2 = data[0, :]

# 2.3 Extract the last column
col2_3 = data[:, -1]

# 2.4 Extract rows 1 and 2, columns 0 and 1
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Select all elements greater than 100 using boolean indexing
filtered_elements2_5 = data[data > 100]

# Display results
print("val2_1 =", val2_1)
print("row2_2 =", row2_2)
print("col2_3 =", col2_3)
print("sub_arr2_4 =\n", sub_arr2_4)
print("filtered_elements2_5 =", filtered_elements2_5)


--- Task 2: Indexing and Slicing with Arrays ---
val2_1 = 120
row2_2 = [10 20 30 40]
col2_3 = [ 40  80 120 160]
sub_arr2_4 =
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5 = [110 120 130 140 150 160]


In [6]:
import numpy as np

print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))  # Random 4x5 array with values 1 to 20

# 3.1 Replace elements less than 10 with 0, keep elements >= 10 unchanged
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count how many elements in arr3_1 are even
even_count3_3 = np.sum(arr3_1 % 2 == 0)

# Display results
print("arr3_1 =\n", arr3_1)
print("arr3_2 =\n", arr3_2)
print("even_count3_3 =", even_count3_3)


--- Task 3: Conditional Operations ---
arr3_1 =
 [[ 7 20  4  6  5]
 [20 18 19 12 17]
 [10  3 19 20 19]
 [ 2  4 19 11  7]]
arr3_2 =
 [[ 0 20  0  0  0]
 [20 18 19 12 17]
 [10  0 19 20 19]
 [ 0  0 19 11  0]]
even_count3_3 = 10


In [7]:
import numpy as np

print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

# 4.1 Calculate the sum of all elements in arr4_1
sum4_1 = np.sum(arr4_1)

# 4.2 Calculate the mean of each column
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3 Find the maximum value in each row
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4 Calculate the standard deviation of the entire array
std4_4 = np.std(arr4_1)

# Display results
print("sum4_1 =", sum4_1)
print("mean_cols4_2 =", mean_cols4_2)
print("max_rows4_3 =", max_rows4_3)
print("std4_4 =", std4_4)


--- Task 4: Aggregation Functions ---
sum4_1 = 84
mean_cols4_2 = [11.          6.66666667 10.33333333]
max_rows4_3 = [12 15 20]
std4_4 = 5.2493385826745405


In [8]:
import numpy as np

print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)  # 1D array from 0 to 23

# 5.1 Reshape arr5_1 into a 4x6 2D array
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2 Reshape arr5_1 into a 2x3x4 3D array
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3 Flatten reshaped_arr5_2 back into a 1D array
# Using ravel()
flattened_arr5_4 = reshaped_arr5_2.ravel()

# Using flatten() (for comparison)
flattened_arr5_4_flatten = reshaped_arr5_2.flatten()

# Display results
print("arr5_1 =", arr5_1)

print("\nreshaped_arr5_2 =\n", reshaped_arr5_2)

print("\nreshaped_arr5_3 =\n", reshaped_arr5_3)

print("\nflattened_arr5_4 using ravel() =", flattened_arr5_4)

print("\nflattened_arr5_4 using flatten() =", flattened_arr5_4_flatten)


--- Task 5: Reshaping and Flattening ---
arr5_1 = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

reshaped_arr5_2 =
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

reshaped_arr5_3 =
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

flattened_arr5_4 using ravel() = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

flattened_arr5_4 using flatten() = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [9]:
import numpy as np

print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the scalar to every element of arr6_1
result6_1 = arr6_1 + scalar

# 6.2 Add the vector to each row of arr6_1
result6_2 = arr6_1 + vector

# Display results
print("arr6_1 =\n", arr6_1)

print("\nresult6_1 =\n", result6_1)

print("\nresult6_2 =\n", result6_2)


--- Task 6: Broadcasting ---
arr6_1 =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

result6_1 =
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

result6_2 =
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [10]:
import numpy as np

print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1 Create a view of original_arr7 using slicing
view_arr7 = original_arr7[:]

# Modify the first element of the view
view_arr7[0] = 99

# Observe original_arr7 changes because view shares the same data
print("After modifying view_arr7:")
print("view_arr7 =", view_arr7)
print("original_arr7 =", original_arr7)

# 7.2 Create a copy of original_arr7 using copy()
copy_arr7 = original_arr7.copy()

# Modify the last element of the copy
copy_arr7[-1] = 0

# Observe original_arr7 remains unchanged
print("\nAfter modifying copy_arr7:")
print("copy_arr7 =", copy_arr7)
print("original_arr7 =", original_arr7)


--- Task 7: Copying vs. Viewing Arrays ---
After modifying view_arr7:
view_arr7 = [99  2  3  4  5]
original_arr7 = [99  2  3  4  5]

After modifying copy_arr7:
copy_arr7 = [99  2  3  4  0]
original_arr7 = [99  2  3  4  5]


In [14]:
import numpy as np

print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

# 8.1 Vertical stacking
vstack_arr8_1 = np.concatenate((arr8_a, arr8_b), axis=0)

# 8.2 Horizontal stacking
hstack_arr8_2 = np.concatenate((arr8_a, arr8_b), axis=1)

# 8.3 Combine vstack_arr8_1 with arr8_c
combined_arr8_3 = np.concatenate((vstack_arr8_1, arr8_c), axis=0)

# 8.4 Split into 3 equal row parts
part1, part2, part3 = np.array_split(combined_arr8_3, 3)

print("vstack_arr8_1:")
print(vstack_arr8_1)

print("\nhstack_arr8_2:")
print(hstack_arr8_2)

print("\ncombined_arr8_3:")
print(combined_arr8_3)

print("\npart1:")
print(part1)

print("\npart2:")
print(part2)

print("\npart3:")
print(part3)


--- Task 8: Stacking and Splitting Arrays ---
vstack_arr8_1:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack_arr8_2:
[[1 2 5 6]
 [3 4 7 8]]

combined_arr8_3:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

part1:
[[1 2]
 [3 4]]

part2:
[[5 6]
 [7 8]]

part3:
[[ 9 10]]


In [15]:
import numpy as np

print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])

arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

# 9.1 Sort arr9_1 in ascending order
sorted_arr9_1 = np.sort(arr9_1)

# 9.2 Sort arr9_2d along columns (each column sorted independently)
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3 Find indices where value 9 is present in arr9_1
idx9_3 = np.where(arr9_1 == 9)

# 9.4 Find index of the maximum value in arr9_1
max_idx9_4 = np.argmax(arr9_1)

# Display results
print("sorted_arr9_1 =", sorted_arr9_1)

print("\nsorted_cols9_2 =\n", sorted_cols9_2)

print("\nidx9_3 =", idx9_3)

print("\nmax_idx9_4 =", max_idx9_4)


--- Task 9: Sorting and Searching ---
sorted_arr9_1 = [1 2 3 4 5 6 7 8 9]

sorted_cols9_2 =
 [[30 20 10]
 [60 50 40]
 [90 80 70]]

idx9_3 = (array([4]),)

max_idx9_4 = 4
