In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")
# Task 1.1: Create a Pandas Series from a list
s1_1 = pd.Series([10, 20, 30, 40, 50])

# Task 1.2: Create a 3x4 NumPy array with random integers between 1 and 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# Task 1.3: Convert the NumPy array into a Pandas DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

# Display the results
print("Series:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame:")
print(df1_3)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------
Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[53 12 16 90]
 [ 1 13 15 14]
 [32 33 80 31]]

DataFrame:
    A   B   C   D
0  53  12  16  90
1   1  13  15  14
2  32  33  80  31


In [2]:
# Task 2: Create a synthetic sales DataFrame

# Create date range (100 days from 2023-01-01 to 2023-04-10)
dates = pd.date_range(start='2023-01-01', periods=100)

# Create DataFrame
df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(['East', 'West', 'North', 'South'], size=100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=100),
    'Sales': np.random.randint(100, 1001, size=100).astype(float),      # Convert to float to allow NaN
    'Quantity': np.random.randint(1, 11, size=100).astype(float)         # Convert to float to allow NaN
})

# Introduce 5 random NaN values in the 'Sales' column
sales_nan_indices = np.random.choice(df_sales.index, size=5, replace=False)
df_sales.loc[sales_nan_indices, 'Sales'] = np.nan

# Introduce 3 random NaN values in the 'Quantity' column
quantity_nan_indices = np.random.choice(df_sales.index, size=3, replace=False)
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan

# Display the first 10 rows
print(df_sales.head(10))

        Date Region   Product  Sales  Quantity
0 2023-01-01  North    Laptop  476.0       2.0
1 2023-01-02  South   Monitor  661.0       4.0
2 2023-01-03   West   Monitor    NaN       1.0
3 2023-01-04  North   Monitor  480.0       1.0
4 2023-01-05  South    Laptop  961.0       4.0
5 2023-01-06   East   Monitor  160.0       5.0
6 2023-01-07  North   Monitor  303.0       4.0
7 2023-01-08   West    Laptop  905.0      10.0
8 2023-01-09   East  Keyboard  164.0       6.0
9 2023-01-10  North     Mouse  983.0       NaN


In [3]:
# Task 3.1: Select only the 'Region' and 'Sales' columns
df3_1 = df_sales[['Region', 'Sales']]

# Task 3.2: Select rows where 'Product' is 'Laptop'
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

# Task 3.3: Select rows where 'Region' is 'East' AND 'Sales' are greater than 500
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]

# Task 3.4: Select the 'Sales' value for the first entry where 'Product' is 'Monitor'
val3_4 = df_sales.loc[df_sales['Product'] == 'Monitor', 'Sales'].iloc[0]

# Display the results
print("Task 3.1:")
print(df3_1.head())

print("\nTask 3.2:")
print(df3_2.head())

print("\nTask 3.3:")
print(df3_3.head())

print("\nTask 3.4:")
print(val3_4)

Task 3.1:
  Region  Sales
0  North  476.0
1  South  661.0
2   West    NaN
3  North  480.0
4  South  961.0

Task 3.2:
         Date Region Product  Sales  Quantity
0  2023-01-01  North  Laptop  476.0       2.0
4  2023-01-05  South  Laptop  961.0       4.0
7  2023-01-08   West  Laptop  905.0      10.0
17 2023-01-18  North  Laptop  848.0       2.0
20 2023-01-21   West  Laptop  800.0      10.0

Task 3.3:
         Date Region   Product  Sales  Quantity
16 2023-01-17   East  Keyboard  828.0      10.0
24 2023-01-25   East  Keyboard  810.0       6.0
27 2023-01-28   East  Keyboard  879.0       8.0
28 2023-01-29   East    Laptop  935.0       1.0
35 2023-02-05   East     Mouse  808.0       1.0

Task 3.4:
661.0


In [4]:
# Task 4.1: Check the number of missing values in each column
missing_counts4_1 = df_sales.isnull().sum()

# Task 4.2: Fill missing 'Sales' values with the mean of the 'Sales' column
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean())

# Task 4.3: Drop rows that have any missing values
df4_3_dropped = df_sales.dropna()

# Display the results
print("Task 4.1: Missing values in each column")
print(missing_counts4_1)

print("\nTask 4.2: DataFrame with missing 'Sales' values filled")
print(df4_2_filled.head())

print("\nTask 4.3: DataFrame after dropping rows with missing values")
print(df4_3_dropped.head())

Task 4.1: Missing values in each column
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

Task 4.2: DataFrame with missing 'Sales' values filled
        Date Region  Product       Sales  Quantity
0 2023-01-01  North   Laptop  476.000000       2.0
1 2023-01-02  South  Monitor  661.000000       4.0
2 2023-01-03   West  Monitor  603.873684       1.0
3 2023-01-04  North  Monitor  480.000000       1.0
4 2023-01-05  South   Laptop  961.000000       4.0

Task 4.3: DataFrame after dropping rows with missing values
        Date Region  Product  Sales  Quantity
0 2023-01-01  North   Laptop  476.0       2.0
1 2023-01-02  South  Monitor  661.0       4.0
3 2023-01-04  North  Monitor  480.0       1.0
4 2023-01-05  South   Laptop  961.0       4.0
5 2023-01-06   East  Monitor  160.0       5.0


In [5]:
# Task 5.1: Create a new column 'Total_Revenue'
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

# Task 5.2: Sort by 'Date' (ascending) and then by 'Sales' (descending)
df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'], ascending=[True, False])

# Task 5.3: Group by 'Region' and calculate the sum of 'Sales' and 'Quantity'
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

# Task 5.4: Group by 'Product' and calculate the average 'Sales'
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

# Display the results
print("Task 5.1: DataFrame with Total_Revenue")
print(df_sales.head())

print("\nTask 5.2: Sorted DataFrame")
print(df5_2_sorted.head())

print("\nTask 5.3: Total Sales and Quantity by Region")
print(df5_3_grouped_region)

print("\nTask 5.4: Average Sales by Product")
print(df5_4_grouped_product)

Task 5.1: DataFrame with Total_Revenue
        Date Region  Product  Sales  Quantity  Total_Revenue
0 2023-01-01  North   Laptop  476.0       2.0          952.0
1 2023-01-02  South  Monitor  661.0       4.0         2644.0
2 2023-01-03   West  Monitor    NaN       1.0            NaN
3 2023-01-04  North  Monitor  480.0       1.0          480.0
4 2023-01-05  South   Laptop  961.0       4.0         3844.0

Task 5.2: Sorted DataFrame
        Date Region  Product  Sales  Quantity  Total_Revenue
0 2023-01-01  North   Laptop  476.0       2.0          952.0
1 2023-01-02  South  Monitor  661.0       4.0         2644.0
2 2023-01-03   West  Monitor    NaN       1.0            NaN
3 2023-01-04  North  Monitor  480.0       1.0          480.0
4 2023-01-05  South   Laptop  961.0       4.0         3844.0

Task 5.3: Total Sales and Quantity by Region
          Sales  Quantity
Region                   
East    17092.0     180.0
North   13903.0     135.0
South   11887.0      80.0
West    14486.0     149.0